language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect:
    username: "ThibautJ"
    access_key: "3b82a5fa-8007-457d-a707-8ab33bf16450"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before-script: node test/event.js
script: npm run ci