ui: "bdd"
language: node_js
node_js:
  - "stable"
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  sauce_connect:
    username: "ThibautJ"
    access_key: "3b82a5fa-8007-457d-a707-8ab33bf16450"
env:
  - CXX=g++-4.8
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
- mocha